### ISSUE TITLE
Analiza sposobu realizacji zapłaty tokenami za usługę

### ISSUE THREAD

**Issue by jkolo** [kpiblockchain/smartevents#5]
Zastanowić się jak miałby wyglądać frontend i backend do płatności za usługi. 

Pytania, które się pojawiły:
1. Jak rezerwować usługi ograniczone ilościowo. 

---

Dedykowana obsługa po stronie kontraktu.

**Comment by jtomkiew-ITM** [comment]
wybranie usługi na frontend'zie powoduje strzał po wykonanie transakcji przelewu tokenów aktualnej organizacji - reszta po stronie backend'u

(czyli nic nie robimy po stronie kontraktu - używamy aktualnych funkcjonalności)
